# SPDX-FileCopyrightText: Alexander Lohnau <alexander.lonau@gmx.de>
# SPDX-License-Identifier: CC0-1.0
Environment:
  KDECI_BUILD: "TRUE"
  CXX: "clang++"

Options:
  setup-dbus-session: False
  require-passing-tests-on: [ '@all' ]
  tests-run-in-parallel: True
  cppcheck-arguments: '-i tests/'
